### ISSUE TITLE
Change to functional java interfaces and implementations

### ISSUE THREAD

**Issue by ea2809** [mork-optimization/mork#148]
**Describe the solution you'd like**
it could be interesting instead of using:
```java
 public interface KMapper<S extends Solution<S, I>, I extends Instance> {
```
we could change the attribute to:
```java
public BiFunction<S extends Solution<S, I>, Integer, Optional<Integer>> kMapper;
```

**Additional context**
We can continue using in the same way the value, but we can use more functions.

Also, using this type of type definition could make all "functions" posible

**CLOSE IT, IF IT IS NOT RELEVANT**

**Comment by rmartinsanta** [comment]
Hi, thanks for the suggestion! Sorry I took so long to take a look at it.

KMapper now implements BiFunction, and should require none or minimal changes when upgrading to the latest Mork version. If you find more examples where standard functional interfaces can be used, do not hesitate to open a new issue or submit a PR directly 😄
