### ISSUE TITLE
Logging and loggers in Mork

### ISSUE THREAD

**Issue by scaverod** [mork-optimization/mork#191]
It is not clear how to use logs in Mork effectively. 

This feature request aims to document the best practices for logging in Mork, such as:

- [ ] how to set up different log levels
- [ ] how to configure the log output,
- [ ]  and how to use the built-in log framework provided by Mork
- among others....

 This would help not so-expert users, as me, to debug and monitor their programs.

**Comment by rmartinsanta** [comment]
Added log docs in https://github.com/mork-optimization/mork/commit/5243a1c4fad6b108717114b3697d913b2724cec8, see the new documentation page at https://docs.mork-optimization.com/en/latest/features/logging/

Any feedback is welcome!

**Comment by rmartinsanta** [comment]
Closing as completed, feel free to reopen if current docs are not enough or additional clarifications are needed.
