### ISSUE TITLE
Local serializers.yml has no preference

### ISSUE THREAD

**Issue by jmcolmenar** [mork-optimization/mork#222]
**Describe the bug**
Properties in a local serializers.yml file have no precedence on the compiled file. Properties in command line do have prevalence.

**To Reproduce**
1. Include a local serializers.yml
2. Change one of the properties like activate/deactivate a serializer, with the opposite value as the compiled one.
3. Run Mork and check the results.

**Expected behavior**
Properties in the local file should prevail, has happens with applications.yml

**What happens instead**
Properties in a local serializers.yml are not taken into account.

**Versions (ignore not applicable ones):**
 - OS: Linux
 - Java version: 
 -- openjdk version "21.0.1" 2023-10-17
 -- OpenJDK Runtime Environment GraalVM CE 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19)
 -- OpenJDK 64-Bit Server VM GraalVM CE 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19, mixed mode, sharing)
 - Mork version (if released, if not commit reference): v0.18

**Comment by rmartinsanta** [comment]
This should be fixed in the upcoming v0.21 version, feel free to reopen if it does not work or if any clarification is needed.
