### ISSUE TITLE
Incomplete Algorithm components documentation

### ISSUE THREAD

**Issue by MRoblesR** [mork-optimization/mork#234]
**Describe the bug**
The docs page [https://docs.mork-optimization.com/en/latest/algorithms/intro/](https://docs.mork-optimization.com/en/latest/algorithms/intro/) is incomplete. Specifically, the section **Component types** has titles without content.

**Screenshots / Code snippets**
![imagen](https://github.com/mork-optimization/mork/assets/21034943/1d636a6e-968b-4891-b31d-f2672c4d499b)

Seen on 2024/02/12.

**Comment by rmartinsanta** [comment]
Updated the doc page and fixed several smaller things along the way. Any feedback is appreciated!
